app:
  page_title: "KAKIQUANT - 云端量化分析终端"
  page_icon: ":bar_chart:"
  layout: "wide"

data:
  data_dir: "/path/to/your/data"

sidebar:
  options:
    - name: "因子数据看板"
      value: "factor_data"
      icon: "bar-chart"
    - name: "AI因子挖掘助手"
      value: "ai_factor"
      icon: "boxes"
    - name: "单因子分析"
      value: "single_factor"
      icon: "caret-right"
    - name: "因子数据库"
      value: "factor_database"
      icon: "file"
    - name: "创建策略向导"
      value: "create_strategy"
      icon: "tools"
    - name: "策略集合"
      value: "strategy_set"
      icon: "archive"
#    - name: "时间序列分析"
#      value: "time_series"
#      icon: "chart-bar"
    - name: "数据下载"
      value: "data_download"
      icon: "cloud-download"
#    - name: "开通会员"
#      value: "open_vip"
#      icon: "credit-card"
#    - name: "关于我们"
#      value: "about_us"
#      icon: "info-circle"
    - name: "设置"
      value: "settings"
      icon: "tools"
    - name: "线上编辑"
      value: "python_editor"
      icon: "code"