app:
  page_title: "KAKIQUANT - Cloud Quantitative Analysis Terminal"
  page_icon: ":bar_chart:"
  layout: "wide"

data:
  data_dir: "/path/to/your/data"

sidebar:
  options:
    - name: "Factor Data Dashboard"
      value: "factor_data"
      icon: "bar-chart"
    - name: "AI Factor Mining Assistant"
      value: "ai_factor"
      icon: "boxes"
    - name: "Single Factor Analysis"
      value: "single_factor"
      icon: "caret-right"
    - name: "Factor Database"
      value: "factor_database"
      icon: "fingerprint"
    - name: "Create Strategy Guide"
      value: "create_strategy"
      icon: "tools"
    - name: "Strategy Set"
      value: "strategy_set"
      icon: "chart-line"
    - name: "Time Series Analysis"
      value: "time_series"
      icon: "chart-bar"
    - name: "Data Download"
      value: "data_download"
      icon: "cloud-download"
    - name: "Open VIP"
      value: "open_vip"
      icon: "credit-card"
    - name: "About Us"
      value: "about_us"
      icon: "info-circle"
